## your personal information from LNMarkets (Rufus15)
lnm_credentials: 
  key: 'QlZ++t74APYMWtnMQKl5QXQlFgdJp7CWUtYMdiaw12k='
  secret: 'P3TF5JA2vk5mPVO6CAeevUe2zVgPrkwb23DxBD9OLTWP4jMi/W3/iaS4wlCu9zbBwJkF2o5dAw6zywgcG++G+A=='
  passphrase: 'fe028bb3h4eb9'
  network: 'testnet'

## choose your strategy while affecting True (and False to other strategies)
strategies:
  #Trading strat based on TA Summary: https://www.tradingview.com/symbols/XBTUSD/technicals/
  ta_summary: True
  

## parameters for strategies
ta_summary:
  quantity: 10 #type=int, min=1, quantity of each open position
  leverage: 10 #type=int, min=1, max=100
  interval: '1m' #type=string, available interval between 2 TA summary signals: "1m", "5m", "15m", "30m", "1h", "2h", "4h", "1d", "1W", "1M"
  timeout: 3 #type=int, min=1, number of minutes the trading strat will be running  


## Other indicators for strats: https://github.com/brian-the-dev/python-tradingview-ta/blob/main/tradingview_ta/main.py

