## your personal information from LNMarkets (Rufus15)
lnm_credentials: 
  key: '+6PFEhoJRuTepnflu/mAEX5rtYZ7zarVPU2bdhHmt4A='
  secret: 'fVK6nI8qbLYBLJzedVsj8mkCaOYbLdHBkDlbY85QRwVsMmmDyvJpKGLPC5N0Phmi6jwPKaWeiTtj0gDp9E7Vng=='
  passphrase: '5j74f5bbaa744'
  network: 'testnet'

## choose your strategy while affecting True (and False to other strategies)
strategies: 
  ta_summary: True
  

## parameters for strategies
ta_summary:
  quantity: 10 #type=int, min=1, quantity of each open position
  leverage: 10 #type=int, min=1, max=100
  interval: '1m' #type=string, available interval between 2 TA summary signals: "1m", "5m", "15m", "30m", "1h", "2h", "4h", "1d", "1W", "1M"


  

